name: LastMonth
run-name: ${{ github.ref }} last_month
on:
  #  schedule:
  #    - cron: "1 * * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: check_lastday_of_month
        run: echo $(date +%d)
