name: LastMonth
run-name: ${{ github.ref }} last_month
on:
  #  schedule:
  #    - cron: "1 * * * *"
  workflow_dispatch:

jobs:
  check_day:
    runs-on: ubuntu-latest
    steps:
      - name: check_first_of_month_or_last_of_month
        run: |
          today=$(date +%d)
          tomorrow=$(date -d "+1 day" +%d)

          if [ $today -eq 01 ]; then
            echo "Today is the 1st day of the month."
          else
            echo "Today is not the 1st day of the month."
          fi

          if [ $tomorrow -eq 01 ]; then
            echo "Tomorrow is the 1st day of the month."
          else
            echo "Tomorrow is not the 1st day of the month."
          fi
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo build

  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo test
