name: LastMonth
run-name: ${{ github.ref }} last_month
on:
  #  schedule:
  #    - cron: "1 * * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps: check_lastday_of_month
      - name: 
        today=$(date +%d)
        tomorrow=$(date -d "tomorrow" +%d)
        if [ $tomorrow -eq 01 ]; then
          echo "Tomorrow is the 1st day of the month."
          # 翌日が1日の場合に実行したいコマンドを追加
        else
          echo "Tomorrow is not the 1st day of the month."
          # 翌日が1日でない場合の処理を追加
        fi