name: LastMonth
run-name: ${{ github.ref }} last_month
on:
  #  schedule:
  #    - cron: "1 * * * *"
  workflow_dispatch:

jobs:
  check_exec_job:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.step1.outputs.result }}
    steps:
      - id: step1
        name: check_first_of_month_or_last_of_month
        run: |
          today=$(date +%d)
          tomorrow=$(date -d "+10 day" +%d)

          result=false
          if [ $today -eq 01 ] || [ $tomorrow -eq 01 ]; then
            retult=true
            echo "true"
          fi
          echo "result=$result" >> "$GITHUB_OUTPUT"

  build:
    runs-on: ubuntu-latest
    needs: check_exec_job
    #    if: ${{ needs.check_exec_job.outputs.result == 'true' }}
    steps:
      - name: build
        run: echo ${{ needs.check_exec_job.outputs.result}}

  test:
    runs-on: ubuntu-latest
    needs: [check_exec_job, build]
    #    if: ${{ needs.check_exec_job.outputs.result == 'true' }}
    steps:
      - name: test
        run: echo test
